export const GET_ALL_ESPECIALIDADES = "GET_ALL_ESPECIALIDADES"
export const GET_ALL_MEDICOS = "GET_ALL_MEDICOS"
export const GET_ALL_HISTORIAL = "GET_ALL_HISTORIAL"
export const GET_ALL_PROGRAMADO = "GET_ALL_PROGRAMADO"

export const GET_ESPECIALIDAD = "GET_ESPECIALIDAD"
